pages:
  image: registry.gitlab.com/gbraad/docugen:latest
  script:
    - mkdir public
    - for f in [0-9]*.md; do pandoc -t html5 --standalone $f -o ./public/${f/%.md}.html; done
    - ls ./public/ | ./genindex.sh > ./index.html
    - mv ./index.html ./public
  artifacts:
    paths:
      - public

